services:
  - type: web
    name: highspeed-lagermanagement
    runtime: node
    plan: free
    region: frankfurt
    nodeVersion: "20.18.1"
    buildCommand: npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
